DefaultContentLanguage = "en"
baseURL = "https://lazeez.tech/"
theme = "introduction"
# googleAnalytics                 = ""

[params]
dateFormat = "Jan 2, 2006"
email = "hello@lazeez.tech"
fadeIn = true
favicon = "/img/favicon.png"
showRSSButton = false
themeStyle = "auto"

[params.home]
introHeight = "fullheight"
localTime = true
timeFormat = "en-US"
timeZone = "Africa/Cairo"

[[menu.main]]
name = "Android App"
url = "https://play.google.com/store/apps/details?id=tech.lazeez.app.crm"

[[menu.main]]
name = "Web App"
url = "https://app.lazeez.tech"

[[menu.main]]
name = "Facebook"
url = "https://www.facebook.com/LazeezTech/"

[[menu.main]]
name = "E-mail"
url = "mailto:hello@lazeez.tech"

[[menu.main]]
name = "Privacy Policy"
url = "/privacy-policy.html"

[languages]
[languages.en]
contentDir = "content/en"
languageCode = "en-us"
languageName = "English"

title = "Lazeez Technologies"
weight = 0

[languages.en.params]
description = "Smart, Light, Modern & Affordable Business Solution"
